### ISSUE TITLE
Question: does `ReactiveEval` work with `ESNextParser`?

### ISSUE THREAD

**Issue by hariprasadiit** [ianchi/espression-rx#12]
Hi,

`ReactiveEval` seems to be extending `ES6Parser`. I've tested `ReactiveEval` with `ESNextParser` and it seems to be working fine even with optional chaining. From the code I can see that optional chaining was implemented in `ESNextParser`. 

Am I missing something here?

**Comment by ianchi** [comment]
`ReactiveEval` extends `ES6StaticEval` which at the moment is the same as `ESNextStaticEval`
So it pretty sure supports the `ESNext…` syntax
